name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["esp32s3"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install Packages
        run: pio pkg install -e ${{ matrix.environment }}

      - name: Generate Merged Bin Path
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            MERGED_BIN_PATH="${{ github.workspace }}/${{ github.event.repository.name }}.${{ matrix.environment }}.${{ github.run_number }}.merged.bin"
          else
            MERGED_BIN_PATH="${{ github.workspace }}/${{ github.event.repository.name }}.${{ matrix.environment }}.${{ github.ref_name }}.merged.bin"
          fi
          echo "MERGED_BIN_PATH: ${MERGED_BIN_PATH}"
          echo "MERGED_BIN_PATH=${MERGED_BIN_PATH}" >> $GITHUB_ENV

      - name: Build PlatformIO Project
        env:
          MERGED_BIN_PATH: ${{ env.MERGED_BIN_PATH }}
        run: |
          pio run -e ${{ matrix.environment }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          name: artifact_${{ matrix.environment }}
          path: ${{ env.MERGED_BIN_PATH }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: _artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: _artifacts/**/*.bin
